In [1]:
import numpy as np

In [2]:
url = 'https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv'

In [3]:
np.arange(1,88,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87])

In [4]:
datos = np.loadtxt(url, delimiter=',', usecols= np.arange(1,6,1), dtype=str)
print(datos)

[['diametro' 'peso' 'rojo' 'verde' 'azul']
 ['2.96' '86.76' '172' '85' '2']
 ['3.91' '88.05' '166' '78' '3']
 ...
 ['15.59' '256.5' '168' '82' '20']
 ['15.92' '260.14' '142' '72' '11']
 ['16.45' '261.51' '152' '74' '2']]


In [5]:
datos = np.loadtxt(url, delimiter=',', usecols=np.arange(1, 6, 1), skiprows=1)
datos

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]], shape=(10000, 5))

In [12]:
suma = np.sum(datos[:, 1])
print("La suma de la columna 2(peso) es:", suma)

producto = np.mean(datos[:, 1])
print("Promedio de la columna 2(peso):", producto.round(2))

La suma de la columna 2(peso) es: 1750507.92
Promedio de la columna 2(peso): 175.05


In [13]:
datos + datos

array([[  5.92, 173.52, 344.  , 170.  ,   4.  ],
       [  7.82, 176.1 , 332.  , 156.  ,   6.  ],
       [  8.84, 190.34, 312.  , 162.  ,   4.  ],
       ...,
       [ 31.18, 513.  , 336.  , 164.  ,  40.  ],
       [ 31.84, 520.28, 284.  , 144.  ,  22.  ],
       [ 32.9 , 523.02, 304.  , 148.  ,   4.  ]], shape=(10000, 5))

In [16]:
datos.mean(axis=0) # Promedio por columnas

array([  9.975685, 175.050792, 153.8478  ,  76.0106  ,  11.3632  ])