## Las listas en Python son estructuras de datos básicas que pueden contener elementos de diferentes tipos (enteros, cadenas, otras listas, etc.). Por otro lado, Numpy (Numerical Python) es una biblioteca de Python que proporciona soporte para matrices multidimensionales, estructuras de datos más avanzadas y eficientes para cálculos numéricos.



### Aquí tienes un ejemplo de cómo convertir una lista en un array Numpy:

In [2]:
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)

Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


Existen varias ventajas en el uso de arrays Numpy en lugar de listas regulares de Python y aquí tienes algunas de ellas:

1. Eficiencia de procesamiento: Las operaciones matemáticas en los arrays Numpy son mucho más rápidas que en las listas regulares, ya que Numpy está optimizado para trabajar con conjuntos de datos homogéneos y libera memoria de la computadora de manera rápida.

2. Facilidad de uso: Las operaciones matemáticas en los arrays Numpy se expresan de manera mucho más clara y concisa que en las listas regulares, lo que hace que el código sea más fácil de leer y mantener.

3. Integración con otras bibliotecas: Numpy es una de las bibliotecas más utilizadas en ciencia de datos y aprendizaje automático. Muchas otras bibliotecas, como Pandas y Matplotlib, están diseñadas para trabajar directamente con arrays Numpy.

Comparación de rendimiento: listas vs arrays

Centrándonos en la eficiencia, podemos comparar el tiempo necesario para realizar un cálculo utilizando listas y arrays.

In [3]:
import numpy as np
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)

Tiempo de la operación con la lista:  0.11051154136657715
Tiempo de la operación con el array:  0.03390955924987793


## Crear Arreglos 3D ceros con forma (2, 3, 4)

In [ ]:
array = np.zeros((2, 3, 4)) # crea un array de ceros con forma (2, 3, 4)
array[0,1,2] = 5 # asigna el valor 5 a la posición (0,1,2) del array
array

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Crear Array Random

In [7]:
array = np.random.rand(3,5) # crea un array 3x5 con valores aleatorios
array

array([[0.30248393, 0.44835595, 0.54662162, 0.00767518, 0.4515344 ],
       [0.3589221 , 0.29851902, 0.64980568, 0.47132431, 0.17974714],
       [0.61803624, 0.40786155, 0.92182456, 0.33172672, 0.29034564]])

In [8]:
array.T # transpone el array, intercambiando filas por columnas

array([[0.30248393, 0.3589221 , 0.61803624],
       [0.44835595, 0.29851902, 0.40786155],
       [0.54662162, 0.64980568, 0.92182456],
       [0.00767518, 0.47132431, 0.33172672],
       [0.4515344 , 0.17974714, 0.29034564]])

# Concatenar Arreglos Horizontalmente

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

array1, array2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [14]:
array_horizontal = np.hstack((array1, array2)) # une los arrays horizontalmente
array_horizontal
 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Concatenar Arreglos Verticales

In [16]:
array_vertical = np.vstack((array1, array2)) # une los arrays verticalmente  
array_vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Operaciones con Arrays

### Calcular la suma de los Elementos

In [21]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])

suma = np.sum(array) # suma todos los elementos del array
suma

np.int64(46)

### Calcular el promedio de los Elementos

In [22]:
promedio = np.mean(array) # calcula el promedio de los elementos del array
promedio

np.float64(5.111111111111111)

### Calcular la mediana de los Elementos

In [23]:
mediana = np.median(array) # calcula la mediana de los elementos del array
mediana

np.float64(5.0)

### Calcular el producto de los Elementos

In [24]:
producto = np.prod(array) # calcula el producto de todos los elementos del array
producto

np.int64(403200)

### Obtener la desviacion estandar de los Elementos

In [25]:
desv_estandard = np.std(array) # calcula la desviación estándar de los elementos del array
desv_estandard

np.float64(2.7666443551086073)

### Obtener la varianza de los Elementos

In [26]:
var = np.var(array) # calcula la varianza de los elementos del array
var

np.float64(7.65432098765432)

### Minimo de los Elementos

In [27]:
minimo = np.min(array) # encuentra el valor mínimo en el array
minimo

np.int64(1)

### Maximo de los Elementos

In [28]:
maximo =np.max(array) # encuentra el valor máximo en el array
maximo

np.int64(10)

### Calcular la suma acumulativa de los Elementos

In [29]:
cumsum = np.cumsum(array) # calcula la suma acumulativa de los elementos del array
cumsum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 46])

# Operaciones Vectoriales

### element-wise

In [30]:
array + array  # suma elemento a elemento

array([ 2,  4,  6,  8, 10, 12, 14, 16, 20])

In [31]:
array - array  # resta elemento a elemento

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
array * array  # multiplicación elemento a elemento

array([  1,   4,   9,  16,  25,  36,  49,  64, 100])

In [33]:
array / array  # división elemento a elemento

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])