## Las listas en Python son estructuras de datos básicas que pueden contener elementos de diferentes tipos (enteros, cadenas, otras listas, etc.). Por otro lado, Numpy (Numerical Python) es una biblioteca de Python que proporciona soporte para matrices multidimensionales, estructuras de datos más avanzadas y eficientes para cálculos numéricos.



### Aquí tienes un ejemplo de cómo convertir una lista en un array Numpy:

In [2]:
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)

Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


Existen varias ventajas en el uso de arrays Numpy en lugar de listas regulares de Python y aquí tienes algunas de ellas:

1. Eficiencia de procesamiento: Las operaciones matemáticas en los arrays Numpy son mucho más rápidas que en las listas regulares, ya que Numpy está optimizado para trabajar con conjuntos de datos homogéneos y libera memoria de la computadora de manera rápida.

2. Facilidad de uso: Las operaciones matemáticas en los arrays Numpy se expresan de manera mucho más clara y concisa que en las listas regulares, lo que hace que el código sea más fácil de leer y mantener.

3. Integración con otras bibliotecas: Numpy es una de las bibliotecas más utilizadas en ciencia de datos y aprendizaje automático. Muchas otras bibliotecas, como Pandas y Matplotlib, están diseñadas para trabajar directamente con arrays Numpy.

Comparación de rendimiento: listas vs arrays

Centrándonos en la eficiencia, podemos comparar el tiempo necesario para realizar un cálculo utilizando listas y arrays.

In [3]:
import numpy as np
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)

Tiempo de la operación con la lista:  0.11051154136657715
Tiempo de la operación con el array:  0.03390955924987793


## Crear Arreglos 3D ceros con forma (2, 3, 4)

In [ ]:
array = np.zeros((2, 3, 4)) # crea un array de ceros con forma (2, 3, 4)
array[0,1,2] = 5 # asigna el valor 5 a la posición (0,1,2) del array
array

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Crear Array Random

In [7]:
array = np.random.rand(3,5) # crea un array 3x5 con valores aleatorios
array

array([[0.30248393, 0.44835595, 0.54662162, 0.00767518, 0.4515344 ],
       [0.3589221 , 0.29851902, 0.64980568, 0.47132431, 0.17974714],
       [0.61803624, 0.40786155, 0.92182456, 0.33172672, 0.29034564]])

In [8]:
array.T # transpone el array, intercambiando filas por columnas

array([[0.30248393, 0.3589221 , 0.61803624],
       [0.44835595, 0.29851902, 0.40786155],
       [0.54662162, 0.64980568, 0.92182456],
       [0.00767518, 0.47132431, 0.33172672],
       [0.4515344 , 0.17974714, 0.29034564]])

# Concatenar Arreglos Horizontalmente

In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

array1, array2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [14]:
array_horizontal = np.hstack((array1, array2)) # une los arrays horizontalmente
array_horizontal
 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [16]:
array_vertical = np.vstack((array1, array2)) # une los arrays verticalmente  
array_vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])